### ISSUE TITLE
how to use rmate in different clients  with a server

### ISSUE THREAD

**Issue by Student-HXJ** [rafaelmaiolla/remote-visual-studio-code#71]
This is my problem: I remote the server with default configuration while my friend also remote the same server(we are different users), I am the first login in the server and I can rmate file in my vscode, when my friend rmate his file then the file unfold on my computer. That’s wield, how can I rmate my file on my computer while my friend rmate his file on his computer and how can I set the configuration?

**Comment by rafaelmaiolla** [comment]
That is happening because both of you are using the same port.

**Comment by Student-HXJ** [comment]
And excuse me , how could I solve this problem , should I set the port in the configuration which is after localhost or -R, or all these port?

**Comment by rafaelmaiolla** [comment]
To avoid any issue, is just easier to change all ports to a new one.

**Comment by Student-HXJ** [comment]
Thank you very much! I have already solved my problem with changing all the ports where it exists.
