### ISSUE TITLE
Como ter acesso ao diretorio?

### ISSUE THREAD

**Issue by edivancarvalho** [rafaelmaiolla/remote-visual-studio-code#79]
Bom dia, não falo inglês ainda mais sei que devo.
Bom, consegir ter acesso ao arquivo, mais qual o comando ou argumento para ter acesso ao repositorio?
aparacere isso.
'/opt/site' is a directory!

e é realmente isso que quero ter acesso ao diretorio pelo vscode, se tive como e o comando for facil colocar o comando logo abaixo da mesange exemplo:
'/opt/CTFd' is a directory!
run: rmate -p 52698 -R /opt/CTFd
esse foi um exemplo.
Obrigado.

**Comment by rafaelmaiolla** [comment]
Bom dia,
Essa extensão só dá acesso a arquivos individuais, e não a um diretório inteiro.

Talvez você queira dar uma olhada em https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack

**Comment by edivancarvalho** [comment]
Opa, Muito Obrigado.
